kind = "mobile"
previewPath = "/"
title = "The 147"
version = "1.0.0"
id = "artifacts/the-147"
router = "expo-domain"

[[integratedSkills]]
name = "expo"
version = "1.0.0"

[[services]]
ensurePreviewReachable = "/status"
name = "expo"
paths = [ "/" ]
localPort = 19289

[services.development]
run = "pnpm --filter @workspace/the-147 run dev"

[services.production]
build = [ "pnpm", "--filter", "@workspace/the-147", "run", "build" ]
run = [ "pnpm", "--filter", "@workspace/the-147", "run", "serve" ]

[services.env]
PORT = "19289"
BASE_PATH = "/"
