// This file is auto-generated by mockupPreviewPlugin.ts.
type ModuleMap = Record<string, () => Promise<Record<string, unknown>>>;
export const modules: ModuleMap = {
  "./components/mockups/ipad-kiosk/Cart.tsx": () => import("../components/mockups/ipad-kiosk/Cart.tsx"),
  "./components/mockups/ipad-kiosk/Home.tsx": () => import("../components/mockups/ipad-kiosk/Home.tsx"),
  "./components/mockups/ipad-kiosk/Menu.tsx": () => import("../components/mockups/ipad-kiosk/Menu.tsx")
};
